version: '3.4'

networks:
  myOverlay:
    external: true

services:
  master:
    image: 10.1.1.147:5000/spark-master:1.0
    depends_on:
      - slave1
      - slave2
      - slave3
    container_name: master
    hostname: master
    networks:
      - myOverlay
    ports:
      - 18080:8080
      - 18042:8042
      - 18088:8088
      - 19888:19888
      - 49707:49707
      - 50070:50070
      - 50075:50075
    tty: true
    deploy:
      replicas: 1
  
  slave1:
    image: 10.1.1.147:5000/spark-slave:1.0
    container_name: slave1
    hostname: slave1
    networks:
      - myOverlay
#    ports:
#      - 8081:8080
#      - 8043:8042
#      - 8089:8088
#      - 19889:19888
#      - 49708:49707
#      - 50071:50070
#      - 50076:50075
    tty: true
    deploy:
      replicas: 1

  slave2:
    image: 10.1.1.147:5000/spark-slave:1.0
    container_name: slave2
    hostname: slave2
    networks:
      - myOverlay
#    ports:
#      - 8082:8080
#      - 8044:8042
#      - 8090:8088
#      - 19890:19888
#      - 49709:49707
#      - 50072:50070
#      - 50077:50075
    tty: true
    deploy:
      replicas: 1

  slave3:
    image: 10.1.1.147:5000/spark-slave:1.0
    container_name: slave3
    hostname: slave3
    networks:
      - myOverlay
#    ports:
#      - 8083:8080
#      - 8045:8042
#      - 8091:8088
#      - 19891:19888
#      - 49710:49707
#      - 50073:50070
#      - 50078:50075
    tty: true
    deploy:
      replicas: 1
